package vn.com.kltn_project_v1.model;

public enum NotificationType {
    INVITE_TO_RESERVATION,
    RESERVATION_REQUEST,
    RESERVATION_UPDATED,
    RESERVATION_CANCELLED,
    CHECKIN_REMINDER,
    APPROVAL_REQUEST,
    FORGOT_CHECKIN,
}
